#!/bin/bash
#
#  Kill the xterms spawed with startXterms
#

CODA_SCRIPTS=/adaqfs/home/sbs-onl/bryan/devel/coda_scripts
. ${CODA_SCRIPTS}/coda_xterms_functions

# Check first for any running remote_vme
rval=$(pgrep -c -U $UID -f "remote_vme")
if [ ! "$rval" == "0" ]; then
    verify_or_die "Kill Xterms"
fi

# Hardcoded CODA_SCRIPTS and CODA_COMPONENT_TABLE
CODA_COMPONENT_TABLE=/adaqfs/home/adaq/Desktop/SBS_coda_scripts/shiftworker_table.cfg
. ${CODA_SCRIPTS}/coda_conf_functions
PATH=${CODA_SCRIPTS}:$PATH

TYPES=( "TS" "ROC" "FPGA" "PEB" "SEB" "ER" "DC" )

for type in ${TYPES[@]}
do
    coda_conf_get_component_list $type
    if [ $? == 1 ] ; then
	hosts=${CODA_HOSTNAME_LIST[@]}

	rval=$(pgrep -c -U $UID -f "remote_vme.*start${type}.sh")

	if [ ! "$rval" == "0" ]; then
	    echo "Killing local start${type}.sh connections"
	    pkill -U $UID -f "remote_vme.*start${type}.sh"
	fi

	case "$type" in
	    "TS" )
		KILLSTRING="coda_ts"
		;;
	    "ROC" | "FPGA" )
		KILLSTRING="coda_roc"
		;;
	    "PEB" | "ER" | "SEB" | "DC" )
		KILLSTRING="-f org.jlab.coda.emu.EmuFactory"
		;;
	esac

	# now kill the ROC, if it's still runnin gon the remote host
	for host in $hosts
	do
	    echo "  Killing $type on $host"
	    ssh -f -l sbs-onl $host pkill $KILLSTRING
	done
    fi

done

exit
