#!/bin/bash
#
# Bash script to start up the RCGUI
#

unset CODA CODA_BIN CODA_LIB

export PATH=`echo $PATH | awk -v RS=: -v ORS=: '/coda/ {next} {print}' | sed 's/:*$//'`
export LD_LIBRARY_PATH=`echo $LD_LIBRARY_PATH | awk -v RS=: -v ORS=: '/coda/ {next} {print}' | sed 's/:*$//'`

export SESSION=sbsts
export EXPID=SBSDAQ

# Hardcoded CODA_SCRIPTS
CODA_SCRIPTS=/adaqfs/home/sbs-onl/bryan/devel/coda_scripts
source ${CODA_SCRIPTS}/setupCODA3.bash
${CODA_BIN}/rcgui
