#!/bin/bash
#
# Bash script to start up Xterm Windows for ROCs and EBs
#
TEST=1

XTERM_EXE="xterm"
XTDIM=80x25
DEF_XINCR=520
DEF_YINCR=380
DEF_YSIZE=3

# These are the first displayed
ROC_XPOS=0
ROC_YPOS=0

# Hardcoded CODA_SCRIPTS and CODA_COMPONENT_TABLE
CODA_SCRIPTS=/adaqfs/home/sbs-onl/bryan/devel/coda_scripts
CODA_COMPONENT_TABLE=config/test/coda_component_table.cfg
. ${CODA_SCRIPTS}/coda_conf_functions
PATH=${CODA_SCRIPTS}:$PATH

# Kill all previous Xterms remnants
#kXterms


set_xterm_title_cmd() {
    local hostname=$1
    local component=$2
    local name=$3
    local option=

    codaconf_get_name_option $hostname $name
    option=$CODA_COMPONENT_OPTION

    XTERM_TITLE="$hostname : $component: $name"
    XTERM_CMD="remote_vme $hostname nobody ${CODA_SCRIPTS}/start$component.sh $name $option"

    case "$component" in
	"ROC" )
	    XTERM_COLOR="lightgreen"
	    ;;
	"FPGA" )
	    XTERM_COLOR="lightgreen"
	    ;;
	"TS" )
	    XTERM_COLOR="yellow"
	    ;;
	"PEB" )
	    XTERM_COLOR="lightblue"
	    ;;
	"ER" )
	    XTERM_COLOR="tan"
	    ;;
	"SEB" )
	    XTERM_COLOR="orange"
	    ;;
	"DC" )
	    XTERM_COLOR="grey"
	    ;;
    esac

    if [ "$TEST" == "1" ]; then
	XTERM_CMD="read"
    fi
}

size=0
last_xpos=0
last_ypos=0
launch_xterm_group() {
    local type=$1
    local xpos=$2
    local xposincr=$3
    local ypos=$4
    local yposincr=$5
    local ysize=$6
    local ypos_orig=$ypos;

    coda_conf_get_component_list $type
    if [ $? == 1 ] ; then
	coda_hosts=${CODA_HOSTNAME_LIST[@]}
	for host in $coda_hosts
	do
	    if [ "$TEST" == "1" ]; then
		echo "x: $xpos  y: $ypos  size: $size"
	    fi

	    codaconf_get_component_name $host $type
	    set_xterm_title_cmd $host $type $CODA_COMPONENT_NAME
	    ${XTERM_EXE} -geometry $XTDIM+$xpos+$ypos -T "$XTERM_TITLE" -bg "$XTERM_COLOR" \
		  -e /bin/bash -c "$XTERM_CMD" &
	    size=$(echo "$size+1" | bc)
	    if [ "$size" == "$ysize" ]; then
		xpos=$(echo "$xpos+$xposincr" | bc)
		ypos=0
		size=0
	    else
		ypos=$(echo "$ypos+$yposincr" | bc)
	    fi
	done

    fi

    last_xpos=$xpos
    last_ypos=$ypos
}

# Launch the ROCs
launch_xterm_group ROC 0 ${DEF_XINCR} 0 ${DEF_YINCR} ${DEF_YSIZE}

# Launch the FPGAs
launch_xterm_group FPGA $last_xpos ${DEF_XINCR} $last_ypos ${DEF_YINCR} ${DEF_YSIZE}

# Launch the TSs
launch_xterm_group TS $last_xpos ${DEF_XINCR} $last_ypos ${DEF_YINCR} ${DEF_YSIZE}

# Launch the PEBs
launch_xterm_group PEB $last_xpos ${DEF_XINCR} $last_ypos ${DEF_YINCR} ${DEF_YSIZE}

# Launch the SEBs
launch_xterm_group SEB $last_xpos ${DEF_XINCR} $last_ypos ${DEF_YINCR} ${DEF_YSIZE}

# Launch the ERs
launch_xterm_group ER $last_xpos ${DEF_XINCR} $last_ypos ${DEF_YINCR} ${DEF_YSIZE}

# Launch the DCs
launch_xterm_group DC $last_xpos ${DEF_XINCR} $last_ypos ${DEF_YINCR} ${DEF_YSIZE}
